name: Refresh Dev Quotes
on:
  schedule:
    - cron: "0 0 * * *" # හැමදාම රෑට automatic update වෙන්න
  workflow_dispatch: # ඕන වෙලාවක manual run කරගන්න
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest # නිවැරදිම Marketplace action path එක
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_languages: yes
          plugin_quotes: yes # Quotes සක්‍රීය කිරීම
