name: Latest YouTube Videos
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

# GitHub එකට README එක write කරන්න අවසර දීම
permissions:
  contents: write

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "youtube-videos"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCFK9phR6Au3AVhUw95n71fQ"
